/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetofinal.gui.telas;

import projetofinal.gui.*;

/**
 *
 * @author samel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Topo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Meio = new javax.swing.JPanel();
        BotGerClient = new javax.swing.JButton();
        BotGerCont = new javax.swing.JButton();
        BotOpBanc = new javax.swing.JButton();
        Rodape = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TELA INICIAL ");
        setPreferredSize(new java.awt.Dimension(800, 500));

        Topo.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setBackground(new java.awt.Color(153, 153, 153));
        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 51, 51));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("SISTEMA BANCARIO");
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout TopoLayout = new javax.swing.GroupLayout(Topo);
        Topo.setLayout(TopoLayout);
        TopoLayout.setHorizontalGroup(
            TopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        TopoLayout.setVerticalGroup(
            TopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopoLayout.createSequentialGroup()
                .addComponent(Titulo)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        getContentPane().add(Topo, java.awt.BorderLayout.PAGE_START);

        Meio.setBackground(new java.awt.Color(255, 255, 255));
        Meio.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        BotGerClient.setText("Gerenciar Clientes ");
        BotGerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerClientActionPerformed(evt);
            }
        });
        Meio.add(BotGerClient);

        BotGerCont.setText("Gerenciar Contas");
        BotGerCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerContActionPerformed(evt);
            }
        });
        Meio.add(BotGerCont);

        BotOpBanc.setText("Operacoes Bancarias");
        BotOpBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotOpBancActionPerformed(evt);
            }
        });
        Meio.add(BotOpBanc);

        getContentPane().add(Meio, java.awt.BorderLayout.CENTER);

        Rodape.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Delegas Bank - Aqui seu dinheiro e mais que valorizado");

        javax.swing.GroupLayout RodapeLayout = new javax.swing.GroupLayout(Rodape);
        Rodape.setLayout(RodapeLayout);
        RodapeLayout.setHorizontalGroup(
            RodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        RodapeLayout.setVerticalGroup(
            RodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RodapeLayout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        getContentPane().add(Rodape, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("TELA INICIAL");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotGerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGerClientActionPerformed
        // TODO add your handling code here:
        new TelaCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotGerClientActionPerformed

    private void BotOpBancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotOpBancActionPerformed
        // TODO add your handling code here:
        new TelaOperacoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotOpBancActionPerformed

    private void BotGerContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGerContActionPerformed
        // TODO add your handling code here:
        new TelaContas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotGerContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotGerClient;
    private javax.swing.JButton BotGerCont;
    private javax.swing.JButton BotOpBanc;
    private javax.swing.JPanel Meio;
    private javax.swing.JPanel Rodape;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel Topo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
