/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.telas;
import javax.swing.JOptionPane;
import gui.GuiController;
import entidades.Conta;
import entidades.ContaCorrente;
import entidades.ContaPoupanca;


/**
 *
 * @author samel
 */
public class TelaSaque extends javax.swing.JDialog {
    private Conta contaAtual = null;

    /**
     * Creates new form TelaSaque
     */
    public TelaSaque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        BotSacar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        LabelConta = new javax.swing.JLabel();
        CampoConta = new javax.swing.JTextField();
        BotBuscar = new javax.swing.JButton();
        LabelTitular = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        LabelTipo = new javax.swing.JLabel();
        LabelSaldo = new javax.swing.JLabel();
        LabelCheque = new javax.swing.JLabel();
        LabelSaque = new javax.swing.JLabel();
        CampoSaque = new javax.swing.JTextField();
        BotSacar = new javax.swing.JButton();
        BotLimpar = new javax.swing.JButton();
        BotCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DELEGAS BANK ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SAQUE EM CONTA");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelConta.setText("Número da conta:");

        BotBuscar.setText("Buscar");
        BotBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarActionPerformed(evt);
            }
        });

        LabelTitular.setText("Titular:");

        LabelCPF.setText("CPF: ");

        LabelTipo.setText("Tipo:");

        LabelSaldo.setText("Saldo disponível:");

        LabelCheque.setText("Saldo Cheque Especial: ");

        LabelSaque.setText("Valor do saque: ");

        CampoSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSaqueActionPerformed(evt);
            }
        });

        BotSacar.setText("Sacar");
        BotSacar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSacarActionPerformed(evt);
            }
        });

        BotLimpar.setText("Limpar");
        BotLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLimparActionPerformed(evt);
            }
        });

        BotCancelar.setText("Cancelar");
        BotCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotBuscar))
                            .addComponent(LabelTitular)
                            .addComponent(LabelCPF)
                            .addComponent(LabelTipo)
                            .addComponent(LabelSaldo)
                            .addComponent(LabelCheque))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotSacar)
                            .addComponent(LabelSaque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoSaque)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(BotCancelar)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelConta)
                    .addComponent(CampoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelCheque)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSaque)
                    .addComponent(CampoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotSacar)
                    .addComponent(BotLimpar)
                    .addComponent(BotCancelar))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSaqueActionPerformed

    private void BotBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarActionPerformed
        // TODO add your handling code here:
        String numero = CampoConta.getText().trim();

    if(numero.isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite o número da conta.");
        return;
    }

    try {
        contaAtual = GuiController.getBancoService().buscarConta(numero);

        LabelTitular.setText("Titular: " + contaAtual.getProprietario().getNome());
        LabelCPF.setText("CPF: " + contaAtual.getProprietario().getCpf());
        LabelTipo.setText("Tipo: " + contaAtual.getTipo());
        LabelSaldo.setText("Saldo: R$ " + String.format("%.2f", contaAtual.getSaldo()));

        // CHEQUE ESPECIAL
        if(contaAtual instanceof ContaCorrente cc){
            LabelCheque.setText("Cheque especial: R$ " + String.format("%.2f", cc.getLimiteChequeEspecial()));
            LabelCheque.setVisible(true);
        } else {
            LabelCheque.setVisible(false);
        }

        BotSacar.setEnabled(true);

    } catch (Exception e){
        JOptionPane.showMessageDialog(this, "Conta não encontrada!");
        BotSacar.setEnabled(false);
    }
    }//GEN-LAST:event_BotBuscarActionPerformed

    private void BotLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLimparActionPerformed
        // TODO add your handling code here:
        CampoConta.setText("");
    CampoSaque.setText("");

    LabelTitular.setText("Titular:");
    LabelCPF.setText("CPF:");
    LabelTipo.setText("Tipo:");
    LabelSaldo.setText("Saldo:");
    LabelCheque.setText("Cheque especial:");
    LabelCheque.setVisible(false);

    contaAtual = null;

    BotSacar.setEnabled(false);
    }//GEN-LAST:event_BotLimparActionPerformed

    private void BotSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSacarActionPerformed
        // TODO add your handling code here:
        if (contaAtual == null) {
        JOptionPane.showMessageDialog(this, "Busque uma conta primeiro!");
        return;
    }

    String textoValor = CampoSaque.getText().trim();

    if (textoValor.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite o valor do saque.");
        return;
    }

    try {
        double valor = Double.parseDouble(textoValor.replace(",", "."));

        if (valor <= 0) {
            JOptionPane.showMessageDialog(this, "Informe um valor maior que zero.");
            return;
        }

        double saldoAtual = contaAtual.getSaldo();

        // =============================
        // CONTA POUPANÇA (sem cheque)
        // =============================
        if (contaAtual instanceof ContaPoupanca) {

            if (saldoAtual < valor) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente!");
                return;
            }

        } 
        
        // =============================
        // CONTA CORRENTE (com cheque)
        // =============================
        else if (contaAtual instanceof ContaCorrente cc) {

            double limite = cc.getLimiteChequeEspecial();

            if (saldoAtual >= valor) {
                // OK - só saldo, sem cheque
            }
            else {
                // PRECISA USAR CHEQUE ESPECIAL
                double necessarioDoCheque = valor - saldoAtual;

                if (necessarioDoCheque > limite) {
                    JOptionPane.showMessageDialog(this, "Saldo insuficiente!");
                    return;
                }

                // =============================
                // ⚠ SOLICITA CONFIRMAÇÃO ⚠
                // =============================
                int opc = JOptionPane.showConfirmDialog(
                    this,
                    "Este saque excede seu saldo.\n" +
                    "Usar R$ " + String.format("%.2f", necessarioDoCheque) + 
                    " do cheque especial?",
                    "Confirmar uso de cheque especial",
                    JOptionPane.YES_NO_OPTION
                );

                if (opc != JOptionPane.YES_OPTION) {
                    return;  // usuário cancelou
                }
            }
        }

        // ======================================
        // EFETIVA O SAQUE NO BANCO
        // ======================================
        GuiController.getBancoService().realizarSaque(
            contaAtual.getNumero(),
            valor
        );

        // Atualiza o saldo real
        double saldoBD = GuiController.getBancoService()
                                     .buscarConta(contaAtual.getNumero())
                                     .getSaldo();

        LabelSaldo.setText("Saldo: R$ " + String.format("%.2f", saldoBD));

        JOptionPane.showMessageDialog(this, "Saque realizado com sucesso!");

        CampoSaque.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Valor inválido.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
    }//GEN-LAST:event_BotSacarActionPerformed

    private void BotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaSaque dialog = new TelaSaque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotBuscar;
    private javax.swing.JButton BotCancelar;
    private javax.swing.JButton BotLimpar;
    private javax.swing.JButton BotSacar;
    private javax.swing.JTextField CampoConta;
    private javax.swing.JTextField CampoSaque;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCheque;
    private javax.swing.JLabel LabelConta;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JLabel LabelSaque;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelTitular;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
