package gui.telas;

import javax.swing.JOptionPane;
import gui.GuiController;
import utilitarios.ClienteNaoEncontradoException;

import java.sql.SQLException;

/**
 *
 * @author samel
 */
public class TelaRemoverCliente extends javax.swing.JDialog {

    /**
     * Creates new form TelaRemoverCliente
     */
    public TelaRemoverCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        CampoCPF = new javax.swing.JTextField();
        BotBuscar = new javax.swing.JButton();
        BoRemover = new javax.swing.JButton();
        BotCancelar = new javax.swing.JButton();
        LabelNome = new javax.swing.JLabel();
        LabelEndereco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover Clientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Remover Clientes");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelCPF.setText("CPF:");

        BotBuscar.setText("Buscar");
        BotBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarActionPerformed(evt);
            }
        });

        BoRemover.setText("Remover");
        BoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoRemoverActionPerformed(evt);
            }
        });

        BotCancelar.setText("Cancelar");
        BotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCancelarActionPerformed(evt);
            }
        });

        LabelNome.setText("Nome:");

        LabelEndereco.setText("Endereço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotBuscar)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotCancelar)
                                .addGap(45, 45, 45))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(LabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCPF)
                    .addComponent(CampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscar))
                .addGap(36, 36, 36)
                .addComponent(LabelNome)
                .addGap(18, 18, 18)
                .addComponent(LabelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoRemover)
                    .addComponent(BotCancelar))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarActionPerformed
        // TODO add your handling code here:
        String cpf = CampoCPF.getText().trim();
        
        if(cpf.isEmpty()){
         JOptionPane.showMessageDialog(this, "Campo CPF nao pode estar vazio");
         return;
        }
        try{
         var cliente = GuiController.getBancoService().buscarCliente(cpf);
         LabelNome.setText("Nome: " + cliente.getNome());
         LabelEndereco.setText("Endereco: " + cliente.getEndereco());
        }
        catch(Exception e){
         JOptionPane.showMessageDialog(this, "Cliente nao encontado");
        }
    }//GEN-LAST:event_BotBuscarActionPerformed

    private void BotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotCancelarActionPerformed

    private void BoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoRemoverActionPerformed
        // TODO add your handling code here:
        String cpf = CampoCPF.getText().trim();
        
        if(cpf.isEmpty()){
        JOptionPane.showMessageDialog(this, "Campo CPF nao pode estar vazio");
        return;
    }
        int resposta = JOptionPane.showConfirmDialog(
            this,
            "Voce tem certeza que deseja remover este cliente?",
            "Confirmar exclusao permanente",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if(resposta != JOptionPane.YES_NO_OPTION){
            return;
        }
        try {
            GuiController.getBancoService().removerCliente(cpf);

            JOptionPane.showMessageDialog(this, "Cliente removido com sucesso!");
            CampoCPF.setText("");
            LabelNome.setText("Nome: ");
            LabelEndereco.setText("Endereco: ");

        } catch (ClienteNaoEncontradoException e) {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro no banco de dados: " + e.getMessage());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); // aqui aparece "Cliente possui contas e não pode ser removido."
        }

    }//GEN-LAST:event_BoRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRemoverCliente dialog = new TelaRemoverCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoRemover;
    private javax.swing.JButton BotBuscar;
    private javax.swing.JButton BotCancelar;
    private javax.swing.JTextField CampoCPF;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
