/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.telas;
import javax.swing.JOptionPane;
import gui.GuiController;
import entidades.Conta;

/**
 *
 * @author samel
 */
public class TelaAlterarConta extends javax.swing.JDialog {
    private entidades.Conta contaAtual = null;

    /**
     * Creates new form TelaAlterarConta
     */
    public TelaAlterarConta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);        
        
        BotAlterar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelNumConta = new javax.swing.JLabel();
        CampoNumConta = new javax.swing.JTextField();
        BotBuscar = new javax.swing.JButton();
        LabelTitularAtual = new javax.swing.JLabel();
        LabelNovoCPF = new javax.swing.JLabel();
        CampoNovoCPF = new javax.swing.JTextField();
        BotAlterar = new javax.swing.JButton();
        BotCancelar = new javax.swing.JButton();
        LabelCPF = new javax.swing.JLabel();
        LabelTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTERAR TITULAR DA CONTA");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelNumConta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNumConta.setText("Número da conta: ");

        CampoNumConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumContaActionPerformed(evt);
            }
        });

        BotBuscar.setText("Buscar");
        BotBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarActionPerformed(evt);
            }
        });

        LabelTitularAtual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTitularAtual.setText("Titular atual da conta: ");

        LabelNovoCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNovoCPF.setText("Novo CPF: ");

        CampoNovoCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNovoCPFActionPerformed(evt);
            }
        });

        BotAlterar.setText("Alterar Titular");
        BotAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAlterarActionPerformed(evt);
            }
        });

        BotCancelar.setText("Cancelar");
        BotCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCancelarActionPerformed(evt);
            }
        });

        LabelCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCPF.setText("CPF atual: ");

        LabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTipo.setText("Tipo da conta: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(BotAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotCancelar)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNumConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotBuscar))
                    .addComponent(LabelTitularAtual)
                    .addComponent(LabelCPF)
                    .addComponent(LabelTipo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNovoCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNovoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumConta)
                    .addComponent(CampoNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelTitularAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTipo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNovoCPF)
                    .addComponent(CampoNovoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotAlterar)
                    .addComponent(BotCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNumContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumContaActionPerformed

    private void CampoNovoCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNovoCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNovoCPFActionPerformed

    private void BotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotCancelarActionPerformed

    private void BotBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarActionPerformed
        String numeroConta = CampoNumConta.getText().trim();

    if(numeroConta.isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite o número da conta.");
        return;
    }

    try {
        contaAtual = GuiController.getBancoService().buscarConta(numeroConta);

        if(contaAtual == null){
            JOptionPane.showMessageDialog(this, "Conta não encontrada!");
            return;
        }

        LabelTitularAtual.setText("Titular atual: " + contaAtual.getProprietario().getNome());
        LabelCPF.setText("CPF atual: " + contaAtual.getProprietario().getCpf());
        LabelTipo.setText("Tipo: " + contaAtual.getTipo());

        BotAlterar.setEnabled(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar conta: " + e.getMessage());
        BotAlterar.setEnabled(false);
    }
    }//GEN-LAST:event_BotBuscarActionPerformed

    private void BotAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAlterarActionPerformed
        if(contaAtual == null){
        JOptionPane.showMessageDialog(this, "Busque uma conta primeiro!");
        return;
    }

    String novoCPF = CampoNovoCPF.getText().trim();

    if(novoCPF.isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite o novo CPF.");
        return;
    }

    try {
        // Verificar cliente existente
        var novoCliente = GuiController.getBancoService().buscarCliente(novoCPF);

        if(novoCliente == null){
            JOptionPane.showMessageDialog(this, "Novo CPF não encontrado na base!");
            return;
        }

        // Confirmação
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Confirmar alteração de titular?\n\n" +
            "Titular atual: " + contaAtual.getProprietario().getNome() +
            "\nNovo titular: " + novoCliente.getNome(),
            "Confirmação",
            JOptionPane.YES_NO_OPTION
        );

        if(resp != JOptionPane.YES_OPTION) return;

        // Alterar no objeto
        contaAtual.setProprietario(novoCliente);

        // Atualizar no BD
        GuiController.getBancoService().atualizarConta(contaAtual);

        // Atualizar Maps (muito importante!)
        GuiController.getBancoService().atualizarMapCliente();
        GuiController.getBancoService().atualizarMapContas();

        JOptionPane.showMessageDialog(this, "Titular alterado com sucesso!");

        // Resetar tela
        CampoNumConta.setText("");
        CampoNovoCPF.setText("");

        LabelTitularAtual.setText("Titular atual:");
        LabelCPF.setText("CPF atual:");
        LabelTipo.setText("Tipo:");

        contaAtual = null;
        BotAlterar.setEnabled(false);

    } catch (Exception e){
        JOptionPane.showMessageDialog(this, "Erro ao alterar: " + e.getMessage());
    }
    }//GEN-LAST:event_BotAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAlterarConta dialog = new TelaAlterarConta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAlterar;
    private javax.swing.JButton BotBuscar;
    private javax.swing.JButton BotCancelar;
    private javax.swing.JTextField CampoNovoCPF;
    private javax.swing.JTextField CampoNumConta;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelNovoCPF;
    private javax.swing.JLabel LabelNumConta;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelTitularAtual;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
