/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.telas;
import gui.GuiController;
import entidades.Conta;
import entidades.ContaCorrente;
import entidades.ContaPoupanca;
import javax.swing.JOptionPane;


/**
 *
 * @author samel
 */
public class TelaTransferencia extends javax.swing.JDialog {
    private Conta contaOrigem = null;
    private Conta contaDestino = null;
    private boolean origemConfirmada = false;
    private boolean destinoConfirmada = false;

    /**
     * Creates new form TelaTransferencia
     */
    public TelaTransferencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LabelOrigem = new javax.swing.JLabel();
        CampoOrigem = new javax.swing.JTextField();
        BotBuscarOrigem = new javax.swing.JButton();
        LabelNomeOrigem = new javax.swing.JLabel();
        LabelCPFOrigem = new javax.swing.JLabel();
        LabelTipoOrigem = new javax.swing.JLabel();
        LabelSaldo = new javax.swing.JLabel();
        LabelCheque = new javax.swing.JLabel();
        BotConfirmarOrigem = new javax.swing.JButton();
        LabelDestino = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CampoDestino = new javax.swing.JTextField();
        BotBuscarDestino = new javax.swing.JButton();
        LabelNomeDestino = new javax.swing.JLabel();
        LabelCPFdestino = new javax.swing.JLabel();
        LabelTipoDestinp = new javax.swing.JLabel();
        BotConfirmarDestino = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        LabelValor = new javax.swing.JLabel();
        CampoValor = new javax.swing.JTextField();
        BotExecutar = new javax.swing.JButton();
        BotLimpar = new javax.swing.JButton();
        BotCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("TRANSFERENCIA ENTRE CONTAS");
        LabelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelOrigem.setText("Número da conta(origem): ");

        CampoOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoOrigemActionPerformed(evt);
            }
        });

        BotBuscarOrigem.setText("Buscar");
        BotBuscarOrigem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotBuscarOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarOrigemActionPerformed(evt);
            }
        });

        LabelNomeOrigem.setText("Nome: ");

        LabelCPFOrigem.setText("CPF:");

        LabelTipoOrigem.setText("Tipo: ");

        LabelSaldo.setText("Saldo:");

        LabelCheque.setText("Cheque Especial:");

        BotConfirmarOrigem.setText("Confirmar");
        BotConfirmarOrigem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotConfirmarOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotConfirmarOrigemActionPerformed(evt);
            }
        });

        LabelDestino.setText("Número da conta(destino):");

        BotBuscarDestino.setText("Buscar");
        BotBuscarDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotBuscarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarDestinoActionPerformed(evt);
            }
        });

        LabelNomeDestino.setText("Nome:");

        LabelCPFdestino.setText("CPF:");

        LabelTipoDestinp.setText("Tipo:");

        BotConfirmarDestino.setText("Confirmar");
        BotConfirmarDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotConfirmarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotConfirmarDestinoActionPerformed(evt);
            }
        });

        LabelValor.setText("Valor de transferencia:");

        BotExecutar.setBackground(new java.awt.Color(204, 255, 204));
        BotExecutar.setForeground(new java.awt.Color(51, 51, 51));
        BotExecutar.setText("Executar");
        BotExecutar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotExecutarActionPerformed(evt);
            }
        });

        BotLimpar.setText("Limpar");
        BotLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLimparActionPerformed(evt);
            }
        });

        BotCancelar.setText("Cancelar");
        BotCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNomeOrigem)
                            .addComponent(LabelCPFOrigem)
                            .addComponent(LabelTipoOrigem)
                            .addComponent(LabelSaldo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCheque)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelOrigem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotBuscarOrigem)
                                    .addComponent(BotConfirmarOrigem)))
                            .addComponent(LabelNomeDestino)
                            .addComponent(LabelCPFdestino))
                        .addContainerGap(8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotBuscarDestino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelTipoDestinp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotConfirmarDestino)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelValor)
                                .addGap(29, 29, 29)
                                .addComponent(CampoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BotExecutar)
                                .addGap(32, 32, 32)
                                .addComponent(BotLimpar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotCancelar)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelOrigem)
                    .addComponent(CampoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscarOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNomeOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCPFOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTipoOrigem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCheque)
                    .addComponent(BotConfirmarOrigem))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDestino)
                    .addComponent(CampoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscarDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelNomeDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelCPFdestino)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipoDestinp)
                    .addComponent(BotConfirmarDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelValor)
                    .addComponent(CampoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotExecutar)
                    .addComponent(BotLimpar)
                    .addComponent(BotCancelar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoOrigemActionPerformed

    private void BotLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLimparActionPerformed
        // TODO add your handling code here:
        CampoOrigem.setText("");
    CampoDestino.setText("");
    CampoValor.setText("");

    LabelNomeOrigem.setText("Nome:");
    LabelCPFOrigem.setText("CPF:");
    LabelTipoOrigem.setText("Tipo:");
    LabelSaldo.setText("Saldo:");
    LabelCheque.setText("Cheque Especial:");

    LabelNomeDestino.setText("Nome:");
    LabelCPFdestino.setText("CPF:");
    LabelTipoDestinp.setText("Tipo:");

    contaOrigem = null;
    contaDestino = null;
    origemConfirmada = false;
    destinoConfirmada = false;

    CampoOrigem.setEnabled(true);
    BotBuscarOrigem.setEnabled(true);
    BotConfirmarOrigem.setEnabled(true);

    CampoDestino.setEnabled(false);
    BotBuscarDestino.setEnabled(false);
    BotConfirmarDestino.setEnabled(false);

    CampoValor.setEnabled(false);
    BotExecutar.setEnabled(false);
    }//GEN-LAST:event_BotLimparActionPerformed

    private void BotBuscarOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarOrigemActionPerformed
        // TODO add your handling code here:
        String numero = CampoOrigem.getText().trim();

    if(numero.isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite o número da conta de origem.");
        return;
    }

    try {
        contaOrigem = GuiController.getBancoService().buscarConta(numero);

        LabelNomeOrigem.setText("Nome: " + contaOrigem.getProprietario().getNome());
        LabelCPFOrigem.setText("CPF: " + contaOrigem.getProprietario().getCpf());
        LabelTipoOrigem.setText("Tipo: " + contaOrigem.getTipo());
        LabelSaldo.setText("Saldo: R$ " + String.format("%.2f", contaOrigem.getSaldo()));

        if(contaOrigem instanceof ContaCorrente cc){
            LabelCheque.setText("Cheque Especial: R$ " + String.format("%.2f", cc.getLimiteChequeEspecial()));
            LabelCheque.setVisible(true);
        } else {
            LabelCheque.setVisible(false);
        }

    } catch (Exception e){
        JOptionPane.showMessageDialog(this, "Conta não encontrada!");
    }
    }//GEN-LAST:event_BotBuscarOrigemActionPerformed

    private void BotConfirmarOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotConfirmarOrigemActionPerformed
        // TODO add your handling code here:
        if(contaOrigem == null){
        JOptionPane.showMessageDialog(this, "Busque uma conta primeiro.");
        return;
    }

    origemConfirmada = true;
    CampoOrigem.setEnabled(false);
    BotBuscarOrigem.setEnabled(false);
    BotConfirmarOrigem.setEnabled(false);

    CampoDestino.setEnabled(true);
    BotBuscarDestino.setEnabled(true);

    JOptionPane.showMessageDialog(this, "Conta de origem confirmada!");
    }//GEN-LAST:event_BotConfirmarOrigemActionPerformed

    private void BotBuscarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarDestinoActionPerformed
        // TODO add your handling code here:
        String numero = CampoDestino.getText().trim();

    if(numero.isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite o número da conta de destino.");
        return;
    }

    try {
        contaDestino = GuiController.getBancoService().buscarConta(numero);

        LabelNomeDestino.setText("Nome: " + contaDestino.getProprietario().getNome());
        LabelCPFdestino.setText("CPF: " + contaDestino.getProprietario().getCpf());
        LabelTipoDestinp.setText("Tipo: " + contaDestino.getTipo());

    } catch (Exception e){
        JOptionPane.showMessageDialog(this, "Conta não encontrada!");
    }
    }//GEN-LAST:event_BotBuscarDestinoActionPerformed

    private void BotConfirmarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotConfirmarDestinoActionPerformed
        // TODO add your handling code here:
            if(contaDestino == null){
        JOptionPane.showMessageDialog(this, "Busque uma conta primeiro.");
        return;
    }

    if(contaOrigem.getNumero().equals(contaDestino.getNumero())){
        JOptionPane.showMessageDialog(this, "Origem e destino não podem ser iguais!");
        return;
    }

    destinoConfirmada = true;

    CampoDestino.setEnabled(false);
    BotBuscarDestino.setEnabled(false);
    BotConfirmarDestino.setEnabled(false);

    CampoValor.setEnabled(true);
    BotExecutar.setEnabled(true);

    JOptionPane.showMessageDialog(this, "Conta de destino confirmada!");
    }//GEN-LAST:event_BotConfirmarDestinoActionPerformed

    private void BotExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotExecutarActionPerformed
        // TODO add your handling code here:
    if(!origemConfirmada || !destinoConfirmada){
        JOptionPane.showMessageDialog(this, "Confirme as contas antes de transferir.");
        return;
    }

    String txt = CampoValor.getText().trim();
    if(txt.isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite o valor da transferência.");
        return;
    }

    try {
        double valor = Double.parseDouble(txt.replace(",", "."));

        if(valor <= 0){
            JOptionPane.showMessageDialog(this, "Informe um valor maior que zero.");
            return;
        }

        double saldo = contaOrigem.getSaldo();
        double limite = 0;
        boolean usarChequeEspecial = false;

        if(contaOrigem instanceof ContaCorrente cc){
            limite = cc.getLimiteChequeEspecial();
        }

        // Verificar se usará cheque especial
        if(valor > saldo){
            usarChequeEspecial = true;
        }

        // Verificação de limite total (saldo + cheque especial)
        if(saldo + limite < valor){
            JOptionPane.showMessageDialog(this, "Saldo insuficiente para transferência!");
            return;
        }

        // ==============================
        // CONFIRMAÇÃO DE USO DO CHEQUE
        // ==============================
        if(usarChequeEspecial){
            double valorUsadoDoCheque = valor - saldo;

            int respCheque = JOptionPane.showConfirmDialog(
                this,
                String.format(
                    "Você está prestes a usar o cheque especial.\n\n" +
                    "Valor da transferência: R$ %.2f\n" +
                    "Saldo disponível:       R$ %.2f\n" +
                    "Valor no cheque:        R$ %.2f\n\n" +
                    "Deseja continuar?",
                    valor, saldo, valorUsadoDoCheque
                ),
                "Confirmar uso do Cheque Especial",
                JOptionPane.YES_NO_OPTION
            );

            if(respCheque != JOptionPane.YES_OPTION){
                return;
            }
        }

        // ==============================
        // CONFIRMAÇÃO DE RESUMO FINAL
        // ==============================
        int respFinal = JOptionPane.showConfirmDialog(
            this,
            "CONFIRMAR TRANSFERÊNCIA?\n\n" +
            "Origem:  " + contaOrigem.getNumero() + " - " + contaOrigem.getProprietario().getNome() + "\n" +
            "Destino: " + contaDestino.getNumero() + " - " + contaDestino.getProprietario().getNome() + "\n" +
            "Valor:   R$ " + String.format("%.2f", valor) + "\n\n" +
            "Deseja executar a operação?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
        );

        if(respFinal != JOptionPane.YES_OPTION){
            return;
        }

        // ==============================
        // REALIZAR TRANSFERÊNCIA
        // ==============================
        GuiController.getBancoService().realizarTransferencia(
                contaOrigem.getNumero(),
                contaDestino.getNumero(),
                valor
        );

        // ==============================
        // ATUALIZAR TELA (recarregar do banco)
        // ==============================
        contaOrigem = GuiController.getBancoService().buscarConta(contaOrigem.getNumero());
        contaDestino = GuiController.getBancoService().buscarConta(contaDestino.getNumero());

        LabelSaldo.setText("Saldo: R$ " + String.format("%.2f", contaOrigem.getSaldo()));

        if(contaOrigem instanceof ContaCorrente ccOrigem){
            LabelCheque.setText("Cheque Especial: R$ " + String.format("%.2f", ccOrigem.getLimiteChequeEspecial()));
        }

        CampoValor.setText("");

        JOptionPane.showMessageDialog(this, "Transferência realizada com sucesso!");

    } catch (NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Valor inválido!");
    } catch (Exception e){
        JOptionPane.showMessageDialog(this, "Erro ao transferir: " + e.getMessage());
    }
    }//GEN-LAST:event_BotExecutarActionPerformed

    private void BotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaTransferencia dialog = new TelaTransferencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotBuscarDestino;
    private javax.swing.JButton BotBuscarOrigem;
    private javax.swing.JButton BotCancelar;
    private javax.swing.JButton BotConfirmarDestino;
    private javax.swing.JButton BotConfirmarOrigem;
    private javax.swing.JButton BotExecutar;
    private javax.swing.JButton BotLimpar;
    private javax.swing.JTextField CampoDestino;
    private javax.swing.JTextField CampoOrigem;
    private javax.swing.JTextField CampoValor;
    private javax.swing.JLabel LabelCPFOrigem;
    private javax.swing.JLabel LabelCPFdestino;
    private javax.swing.JLabel LabelCheque;
    private javax.swing.JLabel LabelDestino;
    private javax.swing.JLabel LabelNomeDestino;
    private javax.swing.JLabel LabelNomeOrigem;
    private javax.swing.JLabel LabelOrigem;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JLabel LabelTipoDestinp;
    private javax.swing.JLabel LabelTipoOrigem;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
