/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.telas;
import javax.swing.JOptionPane; // Para mostrar mensagens
import entidades.Conta;         // Sua classe Conta
import entidades.ContaCorrente;
import gui.GuiController;       // Para acessar o serviço do banco

/**
 *
 * @author samel
 */
public class TelaConsultaSaldo extends javax.swing.JDialog {

    /**
     * Creates new form TelaConsultaSaldo
     */
    public TelaConsultaSaldo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoNumConta = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        LabelNome = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        LabelSaldo = new javax.swing.JLabel();
        LabelTipo = new javax.swing.JLabel();
        BtnFechar = new javax.swing.JButton();
        LabelLimite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAR SALDO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Numero da conta: ");

        CampoNumConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumContaActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        LabelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNome.setText("Nome: ");

        LabelCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCPF.setText("CPF:");

        LabelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelSaldo.setText("Saldo: ");

        LabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTipo.setText("Tipo:");

        BtnFechar.setText("Voltar");
        BtnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFecharActionPerformed(evt);
            }
        });

        LabelLimite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelLimite.setText("Limite Cheque Especial: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCPF)
                            .addComponent(LabelSaldo)
                            .addComponent(LabelTipo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNumConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNome)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelLimite))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(BtnFechar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLimite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnFechar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNumContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumContaActionPerformed

    private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnFecharActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
          String numeroConta = CampoNumConta.getText().trim();

    if (numeroConta.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe o número da conta.");
        return;
    }

    try {
        // Busca a conta pelo número
        entidades.Conta conta = gui.GuiController.getBancoService().buscarConta(numeroConta);

        // Preenche os labels com os dados
        LabelNome.setText("Nome: " + conta.getProprietario().getNome());
        LabelCPF.setText("CPF: " + conta.getProprietario().getCpf());
        LabelTipo.setText("Tipo: " + conta.getTipo());
        LabelSaldo.setText("Saldo: R$ " + String.format("%.2f", conta.getSaldo()));

        // Caso seja conta corrente com limite
        if (conta.getTipo().equalsIgnoreCase("Corrente")) {
            LabelLimite.setText("Limite Cheque Especial: R$ " + String.format("%.2f",conta.getLimiteChequeEspecial()));
        } else {
            LabelLimite.setText("Limite Cheque Especial: Não aplicável");
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Conta não encontrada.");
        // Limpar labels caso erro
        LabelNome.setText("Nome: ");
        LabelCPF.setText("CPF: ");
        LabelTipo.setText("Tipo: ");
        LabelSaldo.setText("Saldo: ");
        LabelLimite.setText("Limite Cheque Especial: ");
    }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaConsultaSaldo dialog = new TelaConsultaSaldo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JTextField CampoNumConta;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelLimite;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
