/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.telas;
import gui.GuiController;
import javax.swing.JOptionPane;


/**
 *
 * @author samel
 */
public class TelaCriarConta extends javax.swing.JDialog {
    public TelaCriarConta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    initComponents();
    setLocationRelativeTo(null);

    CampoLimite.setVisible(false);
    LabelLimite.setVisible(false);

    ComboConta.addActionListener(e -> {
        String tipo = ComboConta.getSelectedItem().toString().trim().toLowerCase();

        if (tipo.equals("corrente")) {
            CampoLimite.setVisible(true);
            LabelLimite.setVisible(true);
        } else {
            CampoLimite.setVisible(false);
            LabelLimite.setVisible(false);
        }
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboConta = new javax.swing.JComboBox<>();
        LabelLimite = new javax.swing.JLabel();
        CampoLimite = new javax.swing.JTextField();
        BotCriar = new javax.swing.JButton();
        BotLimpar = new javax.swing.JButton();
        BotCancelar = new javax.swing.JButton();
        CampoCPF = new javax.swing.JTextField();
        LabelNome = new javax.swing.JLabel();
        LabelEndereco = new javax.swing.JLabel();
        LabelContas = new javax.swing.JLabel();
        BotBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRIAR CONTA");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("CPF Cliente: ");

        jLabel3.setText("Tipo de Conta: ");

        ComboConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "poupanca", "corrente" }));
        ComboConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboContaActionPerformed(evt);
            }
        });

        LabelLimite.setText("Limite Cheque Especial: ");

        CampoLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoLimiteActionPerformed(evt);
            }
        });

        BotCriar.setText("Criar");
        BotCriar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCriarActionPerformed(evt);
            }
        });

        BotLimpar.setText("Limpar");
        BotLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLimparActionPerformed(evt);
            }
        });

        BotCancelar.setText("Cancelar");
        BotCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCancelarActionPerformed(evt);
            }
        });

        LabelNome.setText("Nome:       ");

        LabelEndereco.setText("Endereco:");

        LabelContas.setText("Contas:");

        BotBuscar.setText("Buscar");
        BotBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoCPF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboConta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelLimite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(BotCriar)
                                .addGap(18, 18, 18)
                                .addComponent(BotLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(BotCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelNome))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelContas)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNome)
                .addGap(18, 18, 18)
                .addComponent(LabelEndereco)
                .addGap(18, 18, 18)
                .addComponent(LabelContas)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLimite)
                    .addComponent(CampoLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotCriar)
                    .addComponent(BotLimpar)
                    .addComponent(BotCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCriarActionPerformed
        // TODO add your handling code here:
         try {
        var banco = GuiController.getBancoService();

        String cpf = CampoCPF.getText().trim();
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o CPF.");
            return;
        }

        var cliente = banco.buscarCliente(cpf);
        String tipoConta = ComboConta.getSelectedItem().toString().trim().toLowerCase();

        if (!tipoConta.equals("corrente") && !tipoConta.equals("poupanca")) {
            JOptionPane.showMessageDialog(this, "Selecione um tipo de conta válido.");
            return;
        }

        double limite = 0;
        if (tipoConta.equals("corrente")) {
            String txt = CampoLimite.getText().trim();
            if (txt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o limite do cheque especial.");
                return;
            }
            limite = Double.parseDouble(txt);
        }

        var novaConta = banco.abrirContaCorrente(cliente, tipoConta, limite);
        JOptionPane.showMessageDialog(this, "Conta criada com sucesso!\nNúmero: " + novaConta.getNumero());
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
        
    }//GEN-LAST:event_BotCriarActionPerformed

    private void BotBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarActionPerformed
         try {
        String cpf = CampoCPF.getText().trim();
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF");
            return;
        }

        var banco = GuiController.getBancoService();
        var cliente = banco.buscarCliente(cpf);

        LabelNome.setText("Nome: " + cliente.getNome());
        LabelEndereco.setText("Endereco: " + cliente.getEndereco());
        LabelContas.setText("Contas: " + cliente.getContas().size());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cliente nao encontrado");
    }
    }//GEN-LAST:event_BotBuscarActionPerformed

    private void CampoLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoLimiteActionPerformed

    private void BotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotCancelarActionPerformed

    private void BotLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLimparActionPerformed
    CampoCPF.setText("");
    LabelNome.setText("Nome: ");
    LabelEndereco.setText("Endereco: ");
    LabelContas.setText("Contas: ");
    CampoLimite.setText("");
    ComboConta.setSelectedIndex(0);
    CampoLimite.setVisible(false);
    LabelLimite.setVisible(false);
    }//GEN-LAST:event_BotLimparActionPerformed

    private void ComboContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboContaActionPerformed
        // TODO add your handling code here:
        String tipo = ComboConta.getSelectedItem().toString().trim().toLowerCase();
        
        if (tipo.equals("corrente")) {
        CampoLimite.setVisible(true);
        LabelLimite.setVisible(true);
    } else {
        CampoLimite.setVisible(false);
        LabelLimite.setVisible(false);
    }

    }//GEN-LAST:event_ComboContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCriarConta dialog = new TelaCriarConta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotBuscar;
    private javax.swing.JButton BotCancelar;
    private javax.swing.JButton BotCriar;
    private javax.swing.JButton BotLimpar;
    private javax.swing.JTextField CampoCPF;
    private javax.swing.JTextField CampoLimite;
    private javax.swing.JComboBox<String> ComboConta;
    private javax.swing.JLabel LabelContas;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelLimite;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
