/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.telas;
import javax.swing.JOptionPane;
import gui.GuiController;
import entidades.Conta;


/**
 *
 * @author samel
 */
public class TelaDesativarCOnta extends javax.swing.JDialog {

    /**
     * Creates new form TelaDesativarCOnta
     */
    public TelaDesativarCOnta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        BotDesativar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        LabelDesativarCOnta = new javax.swing.JLabel();
        LabelConta = new javax.swing.JLabel();
        CampoConta = new javax.swing.JTextField();
        BotBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotDesativar = new javax.swing.JButton();
        Retornar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelDesativarCOnta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelDesativarCOnta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDesativarCOnta.setText("Desativar Conta");
        LabelDesativarCOnta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelConta.setText("Numero da conta: ");

        BotBuscar.setText("Buscar");
        BotBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome: ");

        jLabel2.setText("CPF:");

        jLabel3.setText("Saldo:");

        jLabel6.setText("Tipo de conta: ");

        BotDesativar.setBackground(new java.awt.Color(153, 0, 0));
        BotDesativar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotDesativar.setText("Desativar conta");
        BotDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotDesativarActionPerformed(evt);
            }
        });

        Retornar.setText("Retornar");
        Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDesativarCOnta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(BotDesativar)
                        .addGap(18, 18, 18)
                        .addComponent(Retornar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelDesativarCOnta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelConta)
                    .addComponent(CampoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotDesativar)
                    .addComponent(Retornar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotDesativarActionPerformed
         String numeroContaTexto = CampoConta.getText().trim();

    if (numeroContaTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo Número da Conta não pode estar vazio.");
        return;
    }

    try {
        // Buscar conta apenas para mostrar os dados e checar saldo
        Conta conta = GuiController.getBancoService().buscarConta(numeroContaTexto);

        // Confirmação antes de desativar
        int resposta = JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja desativar esta conta?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION
        );

        if (resposta != JOptionPane.YES_OPTION) {
            return; // Usuário cancelou
        }

        // Verifica saldo antes de remover
        if (conta.getSaldo() != 0) {
            JOptionPane.showMessageDialog(this,
                "🔴 A conta possui saldo. É preciso zerar antes de desativar.",
                "Saldo não zerado",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Remover conta usando o número (String)
        GuiController.getBancoService().removerConta(numeroContaTexto);

        JOptionPane.showMessageDialog(this, "Conta desativada com sucesso!");

        // Limpar campos e labels
        CampoConta.setText("");
        jLabel1.setText("Nome:");
        jLabel2.setText("CPF:");
        jLabel3.setText("Saldo:");
        jLabel6.setText("Tipo de conta:");
        BotDesativar.setEnabled(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao desativar a conta: " + e.getMessage());
    }
    }//GEN-LAST:event_BotDesativarActionPerformed

    private void RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_RetornarActionPerformed

    private void BotBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarActionPerformed
        // TODO add your handling code here:
        String numeroTexto = CampoConta.getText().trim();   

    if(numeroTexto.isEmpty()){
        JOptionPane.showMessageDialog(this, "Campo número da conta não pode estar vazio");
        return;
    }

    try{
        String numeroConta = CampoConta.getText().trim();
        var conta = GuiController.getBancoService().buscarConta(numeroConta);

        // Preencher labels
        jLabel1.setText("Nome: " + conta.getProprietario().getNome());
        jLabel2.setText("CPF: " + conta.getProprietario().getCpf());
        jLabel3.setText("Saldo: R$ " + String.format("%.2f", conta.getSaldo()));
        jLabel6.setText("Tipo de conta: " + conta.getNumero());

        // Habilitar ou não o botão de desativar
        if(conta.getSaldo() != 0){
            JOptionPane.showMessageDialog(this,
                "🔴 A conta possui saldo. É preciso zerar antes de desativar.",
                "Saldo não zerado",
                JOptionPane.WARNING_MESSAGE);
            BotDesativar.setEnabled(false);
        } else {
            BotDesativar.setEnabled(true);
        }

    } catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Número da conta inválido");
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Conta não encontrada");
        BotDesativar.setEnabled(false);
    }
    }//GEN-LAST:event_BotBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDesativarCOnta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDesativarCOnta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDesativarCOnta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDesativarCOnta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDesativarCOnta dialog = new TelaDesativarCOnta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotBuscar;
    private javax.swing.JButton BotDesativar;
    private javax.swing.JTextField CampoConta;
    private javax.swing.JLabel LabelConta;
    private javax.swing.JLabel LabelDesativarCOnta;
    private javax.swing.JButton Retornar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
