/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.telas;
import javax.swing.JOptionPane;
import gui.GuiController;

import entidades.Conta;
import entidades.ContaCorrente;
import entidades.ContaPoupanca;

/**
 *
 * @author samel
 */
public class TelaConsultarSaldo extends javax.swing.JDialog {

    /**
     * Creates new form TelaConsultarSaldo
     */
    public TelaConsultarSaldo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        LabelCheque.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelNumConta = new javax.swing.JLabel();
        CampoConta = new javax.swing.JTextField();
        BotBuscar = new javax.swing.JButton();
        LabelTitular = new javax.swing.JLabel();
        LabelTipo = new javax.swing.JLabel();
        LabelCheque = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        BotLimpar = new javax.swing.JButton();
        LabelSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAR SALDO");

        LabelNumConta.setText("Número da conta: ");

        BotBuscar.setText("Buscar");
        BotBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotBuscarActionPerformed(evt);
            }
        });

        LabelTitular.setText("Titular: ");

        LabelTipo.setText("Tipo:");

        LabelCheque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCheque.setText("Lim.Cheque Especial: ");

        LabelCPF.setText("CPF:");

        BotLimpar.setText("Limpar");
        BotLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLimparActionPerformed(evt);
            }
        });

        LabelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelSaldo.setText("Saldo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotLimpar)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTitular)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNumConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotBuscar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LabelCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelCheque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LabelSaldo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumConta)
                    .addComponent(CampoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotBuscar))
                .addGap(18, 18, 18)
                .addComponent(LabelTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCheque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotBuscarActionPerformed
        // TODO add your handling code here:
         String numeroConta = CampoConta.getText().trim();

    if (numeroConta.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite o número da conta.");
        return;
    }

    try {
        var conta = GuiController.getBancoService().buscarConta(numeroConta);

        // TITULAR
        LabelTitular.setText("Titular: " + conta.getProprietario().getNome());
        LabelCPF.setText("CPF: " + conta.getProprietario().getCpf());
        LabelTipo.setText("Tipo: " + conta.getTipo());
        LabelSaldo.setText("Saldo:R$ " + String.format("%.2f", conta.getSaldo()));

        // =============================
        // MOSTRAR OU ESCONDER LIMITE
        // =============================
        if (conta instanceof entidades.ContaCorrente cc) {

            double limite = cc.getLimiteChequeEspecial();

            LabelCheque.setText("Limite Cheque Especial: R$ " + 
                String.format("%.2f", limite));

            LabelCheque.setVisible(true);  // 👈 mostra o label

        } else {
            LabelCheque.setVisible(false); // 👈 esconde o label
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Conta não encontrada!");
    }
    }//GEN-LAST:event_BotBuscarActionPerformed

    private void BotLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLimparActionPerformed
        // TODO add your handling code here:
        // Limpar campo
    CampoConta.setText("");

    // Resetar labels
    LabelTitular.setText("Titular:");
    LabelCPF.setText("CPF:");
    LabelTipo.setText("Tipo:");
    LabelSaldo.setText("Saldo:");

    // Limpar/ocultar cheque especial
    LabelCheque.setText("");
    LabelCheque.setVisible(false);

    BotBuscar.setEnabled(true);
    }//GEN-LAST:event_BotLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaConsultarSaldo dialog = new TelaConsultarSaldo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotBuscar;
    private javax.swing.JButton BotLimpar;
    private javax.swing.JTextField CampoConta;
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCheque;
    private javax.swing.JLabel LabelNumConta;
    private javax.swing.JLabel LabelSaldo;
    private javax.swing.JLabel LabelTipo;
    private javax.swing.JLabel LabelTitular;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
