package gui.telas;

import gui.*;
import util.DBConnection;

public class TelaPrincipal extends javax.swing.JFrame {


    public TelaPrincipal() {
        try {
            DBConnection.inicializar();

            System.out.println("Conexão estabelecida e tabelas prontas!");

            initComponents();
            setLocationRelativeTo(null);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        Topo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Meio = new javax.swing.JPanel();
        BotGerClient = new javax.swing.JButton();
        BotGerCont = new javax.swing.JButton();
        BotOpBanc = new javax.swing.JButton();
        Rodape = new javax.swing.JPanel();
        LabRodape = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA INICIAL ");
        setPreferredSize(new java.awt.Dimension(800, 500));

        Topo.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setBackground(new java.awt.Color(153, 153, 153));
        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 51, 51));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("SISTEMA BANCARIO");
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout TopoLayout = new javax.swing.GroupLayout(Topo);
        Topo.setLayout(TopoLayout);
        TopoLayout.setHorizontalGroup(
            TopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        TopoLayout.setVerticalGroup(
            TopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopoLayout.createSequentialGroup()
                .addComponent(Titulo)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        getContentPane().add(Topo, java.awt.BorderLayout.PAGE_START);

        Meio.setBackground(new java.awt.Color(255, 255, 255));
        Meio.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        BotGerClient.setText("Gerenciar Clientes ");
        BotGerClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotGerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerClientActionPerformed(evt);
            }
        });
        Meio.add(BotGerClient);

        BotGerCont.setText("Gerenciar Contas");
        BotGerCont.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotGerCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGerContActionPerformed(evt);
            }
        });
        Meio.add(BotGerCont);

        BotOpBanc.setText("Operacoes Bancarias");
        BotOpBanc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotOpBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotOpBancActionPerformed(evt);
            }
        });
        Meio.add(BotOpBanc);

        getContentPane().add(Meio, java.awt.BorderLayout.CENTER);

        Rodape.setBackground(new java.awt.Color(255, 255, 255));

        LabRodape.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabRodape.setForeground(new java.awt.Color(51, 51, 51));
        LabRodape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabRodape.setText("Delegas Bank - Aqui seu dinheiro e mais que valorizado");

        javax.swing.GroupLayout RodapeLayout = new javax.swing.GroupLayout(Rodape);
        Rodape.setLayout(RodapeLayout);
        RodapeLayout.setHorizontalGroup(
            RodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabRodape, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        RodapeLayout.setVerticalGroup(
            RodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RodapeLayout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(LabRodape))
        );

        getContentPane().add(Rodape, java.awt.BorderLayout.PAGE_END);
        Rodape.getAccessibleContext().setAccessibleName("Sistema Bancario");

        getAccessibleContext().setAccessibleName("TELA INICIAL");

        pack();
    }

    private void BotGerClientActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        new TelaCliente().setVisible(true);
        this.dispose();
    }

    private void BotOpBancActionPerformed(java.awt.event.ActionEvent evt) {
        new TelaOperacoes().setVisible(true);
        this.dispose();
    }

    private void BotGerContActionPerformed(java.awt.event.ActionEvent evt) {
       
        new TelaContas().setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    private javax.swing.JButton BotGerClient;
    private javax.swing.JButton BotGerCont;
    private javax.swing.JButton BotOpBanc;
    private javax.swing.JLabel LabRodape;
    private javax.swing.JPanel Meio;
    private javax.swing.JPanel Rodape;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel Topo;

}
