package gui.telas;

import gui.*;

/**
 *
 * @author samel
 */
public class TelaOperacoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaOperacoes
     */
    public TelaOperacoes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LabelRodape = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BotDeposito = new javax.swing.JButton();
        BotSaque = new javax.swing.JButton();
        BotTrans = new javax.swing.JButton();
        BotVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("Operações Bancárias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LabelTitulo)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        LabelRodape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRodape.setText("Sistema Bancário • Operações ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelRodape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(LabelRodape))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        BotDeposito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotDeposito.setText("Depósito ");
        BotDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotDepositoActionPerformed(evt);
            }
        });
        jPanel3.add(BotDeposito);

        BotSaque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotSaque.setText("Saque ");
        BotSaque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSaqueActionPerformed(evt);
            }
        });
        jPanel3.add(BotSaque);

        BotTrans.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotTrans.setText("Transferência ");
        BotTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotTransActionPerformed(evt);
            }
        });
        jPanel3.add(BotTrans);

        BotVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotVoltar.setText("Voltar");
        BotVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(BotVoltar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotDepositoActionPerformed
        // TODO add your handling code here:
        new TelaDeposito(this,true).setVisible(true);
    }//GEN-LAST:event_BotDepositoActionPerformed

    private void BotVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotVoltarActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotVoltarActionPerformed

    private void BotSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSaqueActionPerformed
        // TODO add your handling code here:
        new TelaSaque(this,true).setVisible(true);
    }//GEN-LAST:event_BotSaqueActionPerformed

    private void BotTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotTransActionPerformed
        // TODO add your handling code here:
        new TelaTransferencia(this,true).setVisible(true);
    }//GEN-LAST:event_BotTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOperacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotDeposito;
    private javax.swing.JButton BotSaque;
    private javax.swing.JButton BotTrans;
    private javax.swing.JButton BotVoltar;
    private javax.swing.JLabel LabelRodape;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
